package com.autohub.app;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.Color;import android.graphics.Typeface;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.text.InputType;import android.text.Editable;import android.text.TextWatcher;import android.view.*;import android.widget.*;import android.graphics.drawable.GradientDrawable;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import org.json.*;import java.io.*;import java.text.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity{
 AutoDb db; LinearLayout root,content,nav; long active=-1; boolean light=false; String lang="ru"; int blue=Color.rgb(35,153,255);
 final int PICK_PHOTO=1001,PICK_FILE=1002,IMPORT=1003;
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new AutoDb(this);light=getPreferences(0).getBoolean("light",false);lang=getPreferences(0).getString("lang","ru");active=getPreferences(0).getLong("active",-1);if(active<0){Cursor c=db.raw("SELECT id FROM vehicle ORDER BY id LIMIT 1",null);try{if(c.moveToFirst())active=c.getLong(0);}finally{c.close();}}themeBars();build();if(active<0)showWelcome();else home();MileageReminderWorker.ensure(this);DocumentReminderWorker.ensure(this);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},777);}
 void themeBars(){int bg=light?Color.rgb(242,245,248):Color.rgb(7,9,13);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(light?(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR):0);}
 String t(String ru,String en){return "en".equals(lang)?en:ru;}
 int bg(){return light?Color.rgb(242,245,248):Color.rgb(7,9,13);}int fg(){return light?Color.rgb(25,31,38):Color.rgb(245,248,252);}int sub(){return light?Color.rgb(88,101,115):Color.rgb(150,166,184);}int surface(){return light?Color.rgb(248,250,252):Color.rgb(12,18,26);} 
 GradientDrawable glass(int stroke){GradientDrawable g=new GradientDrawable();g.setColor(light?0xEAFBFCFE:0xC9141D27);g.setCornerRadius(dp(20));g.setStroke(dp(1),light?0xB9FFFFFF:0x8863A9E7);return g;}
 TextView text(String s,float size,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextColor(fg());v.setTextSize(size);v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);v.setIncludeFontPadding(true);return v;}
 TextView small(String s){TextView v=text(s,12,false);v.setTextColor(sub());return v;}
 Button btn(String s,int accent){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{accent,Color.rgb(16,104,218)});g.setCornerRadius(dp(15));b.setBackground(g);b.setMinHeight(dp(48));return b;}
 LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(14),dp(16),dp(14));l.setBackground(glass(1));l.setElevation(dp(3));return l;}
 void add(View v){content.addView(v,new LinearLayout.LayoutParams(-1,-2));}
 void addGap(int h){Space s=new Space(this);content.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
 int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg());content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(12),dp(16),dp(24));ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(8),dp(6),dp(8),dp(8));nav.setBackground(glass(1));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(66)));setContentView(root);}
 void nav(){nav.removeAllViews();String[] a={t("Главная","Home"),t("Обслуживание","Service"),t("Финансы","Finance"),t("Авто","Auto"),t("Ещё","More")};for(int i=0;i<a.length;i++){final int p=i;TextView v=text(a[i],10,false);v.setGravity(Gravity.CENTER);v.setTextColor(sub());v.setPadding(0,dp(7),0,dp(5));if((screen==p))v.setTextColor(blue);nav.addView(v,new LinearLayout.LayoutParams(0,-1,1));v.setOnClickListener(x->{screen=p;render();});}}
 int screen=0; int periodDays=0; String pendingAttachment=""; void render(){build();if(screen==0)home();else if(screen==1)serviceScreen();else if(screen==2)financeScreen();else if(screen==3)autoScreen();else moreScreen();nav();}
 String val(String key,String def){Cursor c=db.raw("SELECT "+key+" FROM vehicle WHERE id=?",new String[]{String.valueOf(active)});try{return c.moveToFirst()?c.getString(0):def;}finally{c.close();}}
 double num(String s){try{return Double.parseDouble((s==null?"":s).replace(" ","").replace(",","."));}catch(Exception e){return 0;}}
 String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
 void showWelcome(){build();TextView logo=text("AUTO HUB",31,true);logo.setGravity(Gravity.CENTER);logo.setTextColor(Color.WHITE);content.setGravity(Gravity.CENTER_HORIZONTAL);addGap(60);add(logo);TextView sl=small("Ваш автомобиль —\n"+t("под контролем.","under control."));sl.setGravity(Gravity.CENTER);add(sl);addGap(35);TextView car=text("▰",95,true);car.setGravity(Gravity.CENTER);car.setTextColor(blue);add(car);addGap(20);Button b=btn(t("Начать","Start"),blue);b.setOnClickListener(v->onboarding());add(b);TextView f=small(t("Управляйте. Следите. Экономьте.","Manage. Track. Save."));f.setGravity(Gravity.CENTER);addGap(14);add(f);nav.setVisibility(View.GONE);}
 void onboarding(){build();TextView h=text(t("Добавьте автомобиль","Add vehicle"),28,true);add(h);add(small(t("Минимально обязательны марка, модель и текущий пробег.","Brand, model and current mileage are required.")));addGap(16);vehicleDialog(true);}
 void vehicleDialog(boolean first){final LinearLayout l=form();EditText brand=input(t("Марка","Brand"),first?"":val("brand",""));EditText model=input(t("Модель","Model"),first?"":val("model",""));EditText year=input(t("Год выпуска","Year"),first?"":val("year",""));EditText engine=input(t("Двигатель","Engine"),first?"":val("engine",""));EditText gear=input(t("Коробка передач","Gearbox"),first?"":val("gear",""));EditText mileage=input(t("Текущий пробег, км","Current mileage, km"),first?"0":val("mileage","0"));mileage.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText vin=input("VIN",first?"":val("vin",""));EditText plate=input(t("Госномер","Plate"),first?"":val("plate",""));EditText fuel=input(t("Тип топлива","Fuel type"),first?"":val("fuelType",""));Button photo=btn(t("Добавить фото автомобиля","Add vehicle photo"),Color.rgb(64,103,145));l.addView(photo);photo.setOnClickListener(v->pickPhoto());Button save=btn(t("Сохранить автомобиль","Save vehicle"),blue);l.addView(brand);l.addView(model);l.addView(year);l.addView(engine);l.addView(gear);l.addView(mileage);l.addView(vin);l.addView(plate);l.addView(fuel);l.addView(save);add(l);save.setOnClickListener(v->{if(brand.getText().toString().trim().isEmpty()||model.getText().toString().trim().isEmpty()||num(mileage.getText().toString())<0){toast(t("Заполните марку, модель и корректный пробег","Enter brand, model and a valid mileage"));return;}ContentValues x=new ContentValues();x.put("brand",brand.getText().toString().trim());x.put("model",model.getText().toString().trim());x.put("year",(int)num(year.getText().toString()));x.put("engine",engine.getText().toString().trim());x.put("gear",gear.getText().toString().trim());x.put("mileage",num(mileage.getText().toString()));x.put("vin",vin.getText().toString().trim());x.put("plate",plate.getText().toString().trim());x.put("fuelType",fuel.getText().toString().trim());String chosenPhoto=attachment();x.put("photo",chosenPhoto.isEmpty()?(first?"":val("photo","")):chosenPhoto);x.put("createdAt",System.currentTimeMillis());if(first){active=db.addVehicle(x);getPreferences(0).edit().putLong("active",active).apply();db.log(active,"AUTO","Автомобиль добавлен",brand.getText()+" "+model.getText());screen=0;render();}else{double oldKm=num(val("mileage","0")),newKm=num(mileage.getText().toString());if(newKm<oldKm){new AlertDialog.Builder(this).setTitle("Пробег меньше текущего").setMessage("Новый пробег меньше сохранённого. Изменить его всё равно?").setNegativeButton("Отмена",null).setPositiveButton("Изменить",(dd,ww)->{db.update("vehicle",x,"id=?",new String[]{String.valueOf(active)});render();}).show();}else{db.update("vehicle",x,"id=?",new String[]{String.valueOf(active)});toast(t("Автомобиль сохранён","Vehicle saved"));render();}}});nav.setVisibility(View.GONE);}
 LinearLayout form(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
 EditText input(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setTextColor(fg());e.setHintTextColor(sub());e.setTextSize(15);e.setSingleLine(true);e.setPadding(dp(14),0,dp(14),0);GradientDrawable g=new GradientDrawable();g.setColor(light?0xFFFFFFFF:0xAA0A111A);g.setCornerRadius(dp(13));g.setStroke(dp(1),light?0x33000000:0x665B8FBD);e.setBackground(g);e.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(50)){{setMargins(0,0,0,dp(8));}});return e;}
 void header(String title,String subline){TextView h=text(title,27,true);add(h);if(subline!=null)add(small(subline));addGap(12);}
 void home(){if(active<0){showWelcome();return;}String vehicle=val("brand","")+" "+val("model","");header("AUTO HUB",vehicle.trim());LinearLayout hero=card();TextView ht=text(vehicle.trim(),21,true);hero.addView(ht);ImageView car=new ImageView(this);String carUri=val("photo","");if(carUri.isEmpty())car.setImageResource(R.drawable.car_placeholder);else try{String resolved=resolveAttachment(carUri);if(resolved.startsWith("/"))car.setImageURI(Uri.fromFile(new File(resolved)));else car.setImageURI(Uri.parse(resolved));}catch(Exception ignored){car.setImageResource(R.drawable.car_placeholder);}car.setAdjustViewBounds(true);hero.addView(car,new LinearLayout.LayoutParams(-1,dp(110)));hero.addView(small((val("year","").equals("0")?"":val("year",""))+" · "+(val("engine","").isEmpty()?t("Двигатель не указан","Engine not specified"):val("engine",""))+" · "+(val("gear","").isEmpty()?t("КПП не указана","Gearbox not specified"):val("gear",""))));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView km=text(fmt(num(val("mileage","0")))+" км",31,true);row.addView(km,new LinearLayout.LayoutParams(0,dp(70),1));TextView status=text(healthText(),12,true);status.setTextColor(healthColor());status.setGravity(Gravity.CENTER);row.addView(status,new LinearLayout.LayoutParams(dp(110),dp(50)));hero.addView(row);add(hero);addGap(12);sectionTitle(t("Следующее ТО","Next service"));String next=nextService();add(infoCard(next,blue));addGap(10);sectionTitle(t("Быстрые действия","Quick actions"));LinearLayout q=new LinearLayout(this);q.setOrientation(LinearLayout.VERTICAL);q.addView(actionRow(new String[]{"+ ТО","+ Заправка","+ Расход"},new View.OnClickListener[]{v->serviceDialog(),v->fuelDialog(),v->expenseDialog()}));q.addView(actionRow(new String[]{"+ Напоминание","+ Проблема","+ Шины"},new View.OnClickListener[]{v->reminderDialog(),v->issueDialog(),v->tireDialog()}));add(q);addGap(10);sectionTitle(t("Ключевые показатели","Key metrics"));LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.HORIZONTAL);m.addView(metric(t("Расход","Consumption"),consumption(),"л/100 км"),new LinearLayout.LayoutParams(0,dp(105),1));m.addView(metric(t("Расходы","Expenses"),money(totalExpenses()),"₽"),new LinearLayout.LayoutParams(0,dp(105),1));m.addView(metric(t("Стоимость/км","Cost/km"),costKm(),"₽/км"),new LinearLayout.LayoutParams(0,dp(105),1));add(m);addGap(10);sectionTitle(t("Последняя активность","Recent activity"));activityCards(3);addGap(10);Button manage=btn(t("Открыть полный журнал","Open activity"),blue);manage.setOnClickListener(v->{screen=4;render();});add(manage);}
 View metric(String title,String value,String unit){LinearLayout c=card();c.setPadding(dp(11),dp(10),dp(11),dp(10));c.addView(small(title));TextView b=text(value,18,true);b.setPadding(0,dp(5),0,0);c.addView(b);c.addView(small(unit));return c;}
 View actionRow(String[] labels,View.OnClickListener[] ls){LinearLayout r=new LinearLayout(this);for(int i=0;i<3;i++){Button b=btn(labels[i],i==0?blue:(i==1?Color.rgb(0,177,145):Color.rgb(240,154,44)));b.setTextSize(11);b.setOnClickListener(ls[i]);r.addView(b,new LinearLayout.LayoutParams(0,dp(52),1){{setMargins(dp(3),dp(3),dp(3),dp(3));}});}return r;}
 void sectionTitle(String s){TextView h=text(s,18,true);h.setPadding(0,dp(3),0,dp(6));add(h);}
 TextView infoCard(String s,int color){TextView v=text(s,13,true);v.setPadding(dp(16),dp(16),dp(16),dp(16));GradientDrawable g=glass(1);g.setStroke(dp(1),color);v.setBackground(g);return v;}
 void activityCards(int n){Cursor c=db.raw("SELECT kind,title,detail,date,time FROM activity WHERE vehicleId=? ORDER BY createdAt DESC LIMIT ?",new String[]{String.valueOf(active),String.valueOf(n)});try{while(c.moveToNext()){LinearLayout x=card();x.addView(text(c.getString(1),14,true));x.addView(small(c.getString(3)+" · "+c.getString(4)+" · "+c.getString(2)));x.addView(small(c.getString(3)));add(x);addGap(7);}}finally{c.close();}}
 String nextService(){Cursor c=db.raw("SELECT title,nextDate,nextMileage,mileage FROM service WHERE vehicleId=? AND (nextMileage>0 OR nextDate<>'') ORDER BY id DESC",new String[]{String.valueOf(active)});try{if(!c.moveToFirst())return t("Нет запланированного обслуживания","No planned service");String title=c.getString(0);double nk=c.getDouble(2);String nd=c.getString(1);if(nk>0)return title+" · "+fmt(nk)+" км";return title+" · "+nd;}finally{c.close();}}
 String healthText(){Cursor d=db.raw("SELECT expiryDate FROM document WHERE vehicleId=? AND expiryDate<>''",new String[]{String.valueOf(active)});try{while(d.moveToNext())if(d.getString(0).compareTo(today())<0)return t("КРИТИЧНО","CRITICAL");}finally{d.close();}Cursor svc=db.raw("SELECT nextMileage,nextDate FROM service WHERE vehicleId=?",new String[]{String.valueOf(active)});double currentKm=num(val("mileage","0"));try{while(svc.moveToNext()){double nk=svc.getDouble(0);String nd=svc.getString(1);if((nk>0&&currentKm>=nk)||(nd!=null&&!nd.isEmpty()&&nd.compareTo(today())<0))return t("ПРОСРОЧЕНО","OVERDUE");}}finally{svc.close();}Cursor r=db.raw("SELECT COUNT(*) FROM reminder WHERE vehicleId=? AND done=0 AND date<?",new String[]{String.valueOf(active),today()});try{if(r.moveToFirst()&&r.getInt(0)>0)return t("ПРОСРОЧЕНО","OVERDUE");}finally{r.close();}Cursor p=db.raw("SELECT COUNT(*) FROM issue WHERE vehicleId=? AND status IN ('NEW','DIAGNOSIS','REPAIR')",new String[]{String.valueOf(active)});try{if(p.moveToFirst()&&p.getInt(0)>0)return t("ВНИМАНИЕ","ATTENTION");}finally{p.close();}return t("НОРМА","NORMAL");}
 int healthColor(){String h=healthText();return h.contains("КРИТ")||h.equals("CRITICAL")?Color.rgb(255,74,88):(h.contains("ПРОС")||h.equals("OVERDUE")||h.contains("ВНИМ")||h.equals("ATTENTION")?Color.rgb(255,171,58):Color.rgb(40,207,147));}
 double sumPeriod(String table,String col){if(periodDays<=0)return sum(table,col);String since=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date(System.currentTimeMillis()-periodDays*86400000L));Cursor c=db.raw("SELECT COALESCE(SUM("+col+"),0) FROM "+table+" WHERE vehicleId=? AND date>=?",new String[]{String.valueOf(active),since});try{return c.moveToFirst()?c.getDouble(0):0;}finally{c.close();}}
double totalExpenses(){return sum("expense","amount")+sum("fuel","total")+sum("service","cost");}
 double sum(String table,String col){Cursor c=db.raw("SELECT COALESCE(SUM("+col+"),0) FROM "+table+" WHERE vehicleId=?",new String[]{String.valueOf(active)});try{return c.moveToFirst()?c.getDouble(0):0;}finally{c.close();}}
 String money(double x){return x<0?t("Некорректно","Invalid"):String.format(Locale.getDefault(),"%.0f",x);}
 String consumption(){Cursor c=db.raw("SELECT mileage,liters,fullTank FROM fuel WHERE vehicleId=? ORDER BY mileage,id",new String[]{String.valueOf(active)});double anchorKm=-1,fuelSince=0,totalLit=0,totalDist=0;try{while(c.moveToNext()){double km=c.getDouble(0),l=c.getDouble(1);boolean full=c.getInt(2)!=0;if(km<0||l<0)continue;if(full){if(anchorKm>=0&&km>anchorKm){totalDist+=km-anchorKm;totalLit+=fuelSince+l;}anchorKm=km;fuelSince=0;}else if(anchorKm>=0){fuelSince+=l;}}}finally{c.close();}return totalDist<=0?t("Недостаточно данных","Not enough data"):String.format(Locale.getDefault(),"%.1f",CarMath.consumption(totalLit,totalDist));}
 String costKm(){double dist=distance();return dist<=0?t("Недостаточно данных","Not enough data"):String.format(Locale.getDefault(),"%.2f",CarMath.costPerKm(totalExpenses(),dist));}
 double distance(){Cursor c=db.raw("SELECT MIN(mileage),MAX(mileage) FROM (SELECT mileage FROM fuel WHERE vehicleId=? UNION ALL SELECT mileage FROM service WHERE vehicleId=? UNION ALL SELECT mileage FROM expense WHERE vehicleId=?)",new String[]{String.valueOf(active),String.valueOf(active),String.valueOf(active)});try{if(!c.moveToFirst())return 0;double a=c.getDouble(0),b=c.getDouble(1);return b>a?b-a:0;}finally{c.close();}}
 String fmt(double n){return String.format(Locale.getDefault(),"%.0f",n);}
 void advanceMileage(double km){if(km<=0)return;double cur=num(val("mileage","0"));if(km>cur){ContentValues v=new ContentValues();v.put("mileage",km);db.update("vehicle",v,"id=?",new String[]{String.valueOf(active)});}}
 boolean validDate(String s, boolean allowEmpty){if(s==null||s.trim().isEmpty())return allowEmpty;try{SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.US);f.setLenient(false);f.parse(s.trim());return true;}catch(Exception e){return false;}}
boolean validNonNegative(double x){return !Double.isNaN(x)&&!Double.isInfinite(x)&&x>=0;}
String attachment(){String a=pendingAttachment;if(a==null||a.isEmpty())a=getPreferences(0).getString("pending_attachment","");pendingAttachment="";getPreferences(0).edit().remove("pending_attachment").apply();return a;}
void warnMileageIfLower(double km,Runnable save){double cur=num(val("mileage","0"));if(km<0||Double.isNaN(km)){toast(t("Некорректный пробег","Invalid mileage"));return;}if(km<cur){new AlertDialog.Builder(this).setTitle(t("Пробег меньше текущего","Mileage is lower than current")) .setMessage(t("Сохранить меньший пробег для этой записи? Текущий пробег автомобиля не будет уменьшен автоматически.","Save this lower mileage for the record? The vehicle's current mileage will not be lowered automatically.")) .setNegativeButton(t("Отмена","Cancel"),null).setPositiveButton(t("Сохранить","Save"),(d,w)->save.run()).show();}else save.run();}
void serviceScreen(){header(t("Обслуживание","Service"),t("История и план обслуживания","Service history and plan"));Button add=btn(t("+ Добавить обслуживание","+ Add service"),blue);add.setOnClickListener(v->serviceDialog());add(add);addGap(10);EditText q=input(t("Поиск по обслуживанию…","Search service…"),"");add(q);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);add(list);Runnable run=()->{list.removeAllViews();String needle=q.getText().toString().trim().toLowerCase(Locale.ROOT);Cursor c=db.all("service",active);try{if(!c.moveToFirst()){LinearLayout e=card();e.addView(text(t("Пока нет записей об обслуживании","No service records yet"),14,true));Button b=btn(t("Добавить","Add"),blue);b.setOnClickListener(v->serviceDialog());e.addView(b);list.addView(e);return;}do{String title=c.getString(c.getColumnIndexOrThrow("title"));String cat=c.getString(c.getColumnIndexOrThrow("category"));String all=(title+" "+cat+" "+c.getString(c.getColumnIndexOrThrow("description"))).toLowerCase(Locale.ROOT);if(!needle.isEmpty()&&!all.contains(needle))continue;long id=c.getLong(0);LinearLayout x=card();x.addView(text(title,15,true));x.addView(small(c.getString(c.getColumnIndexOrThrow("date"))+" · "+fmt(c.getDouble(c.getColumnIndexOrThrow("mileage")))+" км"));x.addView(small(cat+" · "+money(c.getDouble(c.getColumnIndexOrThrow("cost")))+" ₽"));Button edit=btn(t("Изменить","Edit"),blue);edit.setOnClickListener(v->serviceDialog(id));x.addView(edit);list.addView(x);Space sp=new Space(this);list.addView(sp,new LinearLayout.LayoutParams(1,dp(7)));}while(c.moveToNext());}finally{c.close();}};q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){run.run();}public void afterTextChanged(Editable e){}});run.run();}
void financeScreen(){header(t("Финансы","Finance"),t("Только сохранённые данные","Saved data only"));LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.HORIZONTAL);int[] days={7,30,90,365,0};String[] labels={"7д","30д","90д","1г","Всё"};for(int i=0;i<labels.length;i++){final int d=days[i];Button b=btn(labels[i],periodDays==d?blue:Color.rgb(55,78,104));b.setTextSize(11);b.setOnClickListener(v->{periodDays=d;render();});p.addView(b,new LinearLayout.LayoutParams(0,dp(45),1){{setMargins(dp(2),0,dp(2),0);}});}add(p);addGap(10);LinearLayout sum=card();double exp=sumPeriod("expense","amount");double fuel=sumPeriod("fuel","total");double svc=sumPeriod("service","cost");sum.addView(small(t("Расходы за период","Expenses for period")));sum.addView(text(money(exp+fuel+svc)+" ₽",30,true));sum.addView(small(t("ТО: ","Service: ")+money(svc)+" ₽ · "+t("Топливо: ","Fuel: ")+money(fuel)+" ₽ · "+t("Прочее: ","Other: ")+money(exp)+" ₽"));add(sum);addGap(10);Button e=btn(t("+ Добавить расход","+ Add expense"),blue);e.setOnClickListener(v->expenseDialog());add(e);Button f=btn(t("+ Добавить заправку","+ Add fuel"),Color.rgb(0,177,145));f.setOnClickListener(v->fuelDialog());add(f);addGap(10);sectionTitle(t("Стоимость километра","Cost per km"));add(infoCard(costKm()+" ₽/км",blue));addGap(10);sectionTitle(t("Последние расходы","Recent expenses"));listSimple("expense","title","amount");}
void autoScreen(){header(t("Авто","Vehicle"),t("Профиль активного автомобиля","Active vehicle profile"));Button edit=btn(t("Редактировать автомобиль","Edit vehicle"),blue);edit.setOnClickListener(v->editVehicle());add(edit);Button del=btn(t("Удалить автомобиль","Delete vehicle"),Color.rgb(180,45,55));del.setOnClickListener(v->confirmDeleteVehicle());add(del);addGap(10);LinearLayout x=card();String[] fields={"brand","model","year","engine","gear","mileage","vin","plate","fuelType"};String[] labels={"Марка","Модель","Год","Двигатель","КПП","Пробег","VIN","Госномер","Топливо"};for(int i=0;i<fields.length;i++){TextView r=small(labels[i]+": "+val(fields[i],"—"));r.setTextSize(14);r.setTextColor(fg());x.addView(r,new LinearLayout.LayoutParams(-1,dp(35)));}add(x);addGap(10);Button docs=btn(t("Документы","Documents"),blue);docs.setOnClickListener(v->documentScreen());add(docs);Button tires=btn(t("Шины","Tires"),blue);tires.setOnClickListener(v->tireScreen());add(tires);Button issues=btn(t("Проблемы","Issues"),Color.rgb(255,74,88));issues.setOnClickListener(v->issueScreen());add(issues);Button parts=btn(t("Запчасти","Parts"),blue);parts.setOnClickListener(v->partScreen());add(parts);Button centers=btn(t("Сервисы / СТО","Service centers"),blue);centers.setOnClickListener(v->centerScreen());add(centers);Button stats=btn(t("Статистика","Statistics"),blue);stats.setOnClickListener(v->statisticsScreen());add(stats);}
 void moreScreen(){header(t("Ещё","More"),t("Инструменты и настройки","Tools and settings"));Button search=btn(t("Поиск по данным","Search data"),blue);search.setOnClickListener(v->searchScreen());add(search);Button rem=btn(t("Напоминания","Reminders"),blue);rem.setOnClickListener(v->reminderScreen());add(rem);Button activity=btn(t("Лента активности","Activity timeline"),blue);activity.setOnClickListener(v->activityScreen());add(activity);Button backup=btn(t("Резервная копия / экспорт JSON","Backup / JSON export"),blue);backup.setOnClickListener(v->exportBackup());add(backup);Button full=btn(t("Полная копия ZIP (данные + файлы)","Full ZIP backup (data + files)"),Color.rgb(64,103,145));full.setOnClickListener(v->exportFullBackup());add(full);Button imp=btn(t("Импорт JSON","Import JSON"),blue);imp.setOnClickListener(v->importBackup());add(imp);Button impFull=btn(t("Импорт полной копии ZIP","Import full ZIP backup"),Color.rgb(64,103,145));impFull.setOnClickListener(v->importFullBackup());add(impFull);Button switchCar=btn(t("Переключить автомобиль","Switch vehicle"),blue);switchCar.setOnClickListener(v->switchVehicle());add(switchCar);Button newCar=btn(t("Добавить автомобиль","Add vehicle"),blue);newCar.setOnClickListener(v->vehicleDialog(true));add(newCar);Button theme=btn(light?t("Включить тёмную тему","Enable dark theme"):t("Включить светлую тему","Enable light theme"),Color.rgb(64,103,145));theme.setOnClickListener(v->{light=!light;getPreferences(0).edit().putBoolean("light",light).apply();themeBars();render();});add(theme);Button language=btn("RU / EN",blue);language.setOnClickListener(v->{lang="en".equals(lang)?"ru":"en";getPreferences(0).edit().putString("lang",lang).apply();render();});add(language);addGap(15);add(small("AUTO HUB 2.1.0 · local-first · no fake OBD/GPS"));}
 void searchBox(String table){EditText q=input(t("Поиск по записям…","Search records…"),"");add(q);q.setOnEditorActionListener((v,a,e)->{toast(t("Поиск используется для фильтрации локальных данных","Search filters local data"));return false;});}
 void listSimple(String table,String titleCol,String amountCol){Cursor c=db.all(table,active);try{int n=0;while(c.moveToNext()&&n<10){LinearLayout x=card();x.addView(text(c.getString(c.getColumnIndexOrThrow(titleCol)),14,true));if(amountCol!=null)x.addView(small(money(c.getDouble(c.getColumnIndexOrThrow(amountCol)))+" ₽ · "+c.getString(c.getColumnIndexOrThrow("date"))));add(x);addGap(7);n++;}}finally{c.close();}}
 void empty(String s,Runnable r){LinearLayout x=card();x.setGravity(Gravity.CENTER);x.addView(text(s,14,true));Button b=btn(t("Добавить","Add"),blue);b.setOnClickListener(v->r.run());x.addView(b);add(x);}
 void serviceDialog(){serviceDialog(-1);}void serviceDialog(long id){final LinearLayout l=form();Cursor old=id>0?db.raw("SELECT * FROM service WHERE id=?",new String[]{String.valueOf(id)}):null;JSONObject o=row(old);if(old!=null)old.close();EditText title=input(t("Название работы","Service title"),o.optString("title",""));EditText date=input(t("Дата YYYY-MM-DD","Date YYYY-MM-DD"),o.optString("date",today()));EditText km=input(t("Пробег, км","Mileage, km"),fmt(o.optDouble("mileage",num(val("mileage","0")))));EditText cat=input(t("Категория","Category"),o.optString("category","Другое"));EditText cost=input(t("Стоимость, ₽","Cost, ₽"),fmt(o.optDouble("cost",0)));EditText desc=input(t("Описание","Description"),o.optString("description",""));EditText center=input(t("Сервис","Service center"),o.optString("center",""));EditText nextKm=input(t("Следующее ТО, км","Next service mileage"),o.optDouble("nextMileage",0)>0?fmt(o.optDouble("nextMileage",0)):"");EditText nextDate=input(t("Следующее ТО, дата","Next service date"),o.optString("nextDate",""));for(EditText e:new EditText[]{title,date,km,cat,cost,desc,center,nextKm,nextDate})l.addView(e);Button save=btn(t("Сохранить","Save"),blue);l.addView(save);if(id>0){Button del=btn(t("Удалить","Delete"),Color.rgb(180,45,55));l.addView(del);del.setOnClickListener(v->confirmDelete("service",id));}addDialogCard(t("Обслуживание","Service"),l);save.setOnClickListener(v->{ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("date",date.getText().toString());x.put("mileage",num(km.getText().toString()));x.put("category",cat.getText().toString());x.put("title",title.getText().toString());x.put("description",desc.getText().toString());x.put("cost",num(cost.getText().toString()));x.put("center",center.getText().toString());x.put("nextMileage",num(nextKm.getText().toString()));x.put("nextDate",nextDate.getText().toString());if(id>0)db.update("service",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("service",x);db.log(active,"ТО",title.getText().toString(),money(num(cost.getText().toString()))+" ₽");}advanceMileage(num(km.getText().toString()));toast(t("Обслуживание сохранено","Service saved"));render();});}
 void addDialogCard(String title,LinearLayout l){content.removeAllViews();Button back=btn("‹ "+t("Назад","Back"),Color.rgb(55,78,104));back.setOnClickListener(v->{render();});add(back);addGap(8);header(title,null);add(l);}
 JSONObject row(Cursor c){JSONObject o=new JSONObject();if(c==null||!c.moveToFirst())return o;for(int i=0;i<c.getColumnCount();i++)try{o.put(c.getColumnName(i),c.getString(i));}catch(Exception ignored){}return o;}
 void fuelDialog(){fuelDialog(-1);}void fuelDialog(long id){final LinearLayout l=form();JSONObject o=new JSONObject();Cursor old=id>0?db.raw("SELECT * FROM fuel WHERE id=?",new String[]{String.valueOf(id)}):null;o=row(old);if(old!=null)old.close();EditText date=input("Дата YYYY-MM-DD",o.optString("date",today())),km=input("Пробег, км",fmt(o.optDouble("mileage",num(val("mileage","0"))))),lit=input("Литры",fmt(o.optDouble("liters",0))),price=input("Цена за литр, ₽",fmt(o.optDouble("price",0))),type=input("Тип топлива",o.optString("type","АИ-95")),station=input("АЗС",o.optString("station","")),full=input("Полный бак: 1 = да, 0 = нет",o.optInt("fullTank",1)+"");for(EditText e:new EditText[]{date,km,lit,price,type,station,full})l.addView(e);Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("fuel",id));}addDialogCard("Заправка",l);save.setOnClickListener(v->{double L=num(lit.getText().toString()),P=num(price.getText().toString()),K=num(km.getText().toString());if(L<=0||P<0){toast("Введите корректные литры и цену");return;}ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("date",date.getText().toString());x.put("mileage",K);x.put("liters",L);x.put("price",P);x.put("total",CarMath.total(L,P));x.put("type",type.getText().toString());x.put("station",station.getText().toString());x.put("fullTank",(int)num(full.getText().toString()));if(id>0)db.update("fuel",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("fuel",x);db.log(active,"ЗАПРАВКА",type.getText().toString(),String.format(Locale.getDefault(),"%.1f л · %.0f ₽",L,L*P));}advanceMileage(K);render();});}
 void expenseDialog(){expenseDialog(-1);}void expenseDialog(long id){LinearLayout l=form();JSONObject o=new JSONObject();Cursor old=id>0?db.raw("SELECT * FROM expense WHERE id=?",new String[]{String.valueOf(id)}):null;o=row(old);if(old!=null)old.close();EditText date=input("Дата YYYY-MM-DD",o.optString("date",today())),km=input("Пробег, км",fmt(o.optDouble("mileage",num(val("mileage","0"))))),cat=input("Категория","ТО / Ремонт / Топливо / Шины / Страховка / Налог / Штраф / Мойка / Парковка / Запчасти / Диагностика / Прочее"),title=input("Название",o.optString("title","")),amount=input("Сумма, ₽",fmt(o.optDouble("amount",0))),note=input("Комментарий",o.optString("note",""));for(EditText e:new EditText[]{date,km,cat,title,amount,note})l.addView(e);Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("expense",id));}addDialogCard("Расход",l);save.setOnClickListener(v->{double a=num(amount.getText().toString());if(a<0){toast("Сумма не может быть отрицательной");return;}ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("date",date.getText().toString());x.put("mileage",num(km.getText().toString()));x.put("category",cat.getText().toString());x.put("title",title.getText().toString());x.put("amount",a);x.put("note",note.getText().toString());if(id>0)db.update("expense",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("expense",x);db.log(active,"РАСХОД",title.getText().toString(),money(a)+" ₽");}advanceMileage(num(km.getText().toString()));render();});}
 void reminderDialog(){reminderDialog(-1);}void reminderDialog(long id){LinearLayout l=form();JSONObject o=new JSONObject();Cursor old=id>0?db.raw("SELECT * FROM reminder WHERE id=?",new String[]{String.valueOf(id)}):null;o=row(old);if(old!=null)old.close();EditText title=input("Что напомнить",o.optString("title","")),date=input("Дата YYYY-MM-DD (необязательно)",o.optString("date","")),km=input("Пробег, км (необязательно)",o.optDouble("mileage",0)>0?fmt(o.optDouble("mileage",0)):""),repeat=input("Повтор, дней (0 = один раз)",fmt(o.optDouble("repeatDays",0)));for(EditText e:new EditText[]{title,date,km,repeat})l.addView(e);Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("reminder",id));}addDialogCard("Напоминание",l);save.setOnClickListener(v->{String titleText=title.getText().toString().trim(),ds=date.getText().toString().trim();double targetKm=num(km.getText().toString());int rep=(int)num(repeat.getText().toString());if(titleText.isEmpty()){toast("Укажите текст напоминания");return;}if(!validDate(ds,true)){toast("Неверная дата. Используйте YYYY-MM-DD");return;}if(ds.isEmpty()&&targetKm<=0){toast("Укажите дату или пробег");return;}if(targetKm<0||rep<0){toast("Пробег и повтор не могут быть отрицательными");return;}ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("title",titleText);x.put("date",ds);x.put("mileage",targetKm);x.put("repeatDays",rep);x.put("done",0);x.put("createdAt",System.currentTimeMillis());x.put("lastMileageNotified",0);long reminderId=id;if(id>0){db.update("reminder",x,"id=?",new String[]{String.valueOf(id)});ReminderWorker.cancel(this,id);}else reminderId=db.insert("reminder",x);if(!ds.isEmpty()){try{long when=new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(ds).getTime();ReminderWorker.schedule(this,reminderId,titleText,Math.max(0,when-System.currentTimeMillis()),rep);}catch(Exception ex){toast("Не удалось запланировать дату");return;}}db.log(active,"НАПОМИНАНИЕ",titleText,ds.isEmpty()?"Пробег: "+fmt(targetKm)+" км":ds);render();});}
void issueDialog(){issueDialog(-1);}void issueDialog(long id){LinearLayout l=form();Cursor old=id>0?db.raw("SELECT * FROM issue WHERE id=?",new String[]{String.valueOf(id)}):null;final JSONObject o=row(old);if(old!=null)old.close();Button photo=btn("Добавить фото",Color.rgb(64,103,145));l.addView(photo);photo.setOnClickListener(v->pickPhoto());EditText title=input("Проблема",o.optString("title","")),desc=input("Описание",o.optString("description","")),date=input("Дата YYYY-MM-DD",o.optString("date",today())),km=input("Пробег, км",fmt(o.optDouble("mileage",num(val("mileage","0"))))),sym=input("Симптомы",o.optString("symptoms","")),status=input("Статус: NEW / DIAGNOSIS / REPAIR / RESOLVED",o.optString("status","NEW")),cost=input("Стоимость, ₽",fmt(o.optDouble("cost",0))),resolution=input("Решение",o.optString("resolution",""));for(EditText e:new EditText[]{title,desc,date,km,sym,status,cost,resolution})l.addView(e);Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("issue",id));}addDialogCard("Проблема",l);save.setOnClickListener(v->{ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("title",title.getText().toString());x.put("description",desc.getText().toString());x.put("date",date.getText().toString());x.put("mileage",num(km.getText().toString()));x.put("symptoms",sym.getText().toString());x.put("status",status.getText().toString().trim().toUpperCase(Locale.US));x.put("cost",num(cost.getText().toString()));x.put("resolution",resolution.getText().toString());String chosenPhoto=attachment();x.put("photo",chosenPhoto.isEmpty()?o.optString("photo",""):chosenPhoto);if(id>0)db.update("issue",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("issue",x);db.log(active,"ПРОБЛЕМА",title.getText().toString(),status.getText().toString());}render();});}
 void tireDialog(){tireDialog(-1);}void tireDialog(long id){LinearLayout l=form();JSONObject o=new JSONObject();Cursor old=id>0?db.raw("SELECT * FROM tire WHERE id=?",new String[]{String.valueOf(id)}):null;o=row(old);if(old!=null)old.close();EditText season=input("Сезон: Лето / Зима / Всесезон",o.optString("season","Лето")),brand=input("Бренд",o.optString("brand","")),model=input("Модель",o.optString("model","")),size=input("Размер",o.optString("size","")),buyDate=input("Дата покупки",o.optString("purchaseDate","")),install=input("Дата установки",o.optString("installDate","")),tread=input("Глубина протектора, мм",o.optDouble("tread",0)>0?fmt(o.optDouble("tread",0)):""),pressure=input("Давление",o.optString("pressure","")),storage=input("Хранение",o.optString("storage","")),cost=input("Стоимость, ₽",fmt(o.optDouble("cost",0))),installed=input("Установлен: 1/0",o.optInt("installed",0)+"");for(EditText e:new EditText[]{season,brand,model,size,buyDate,install,tread,pressure,storage,cost,installed})l.addView(e);Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("tire",id));}addDialogCard("Шины",l);save.setOnClickListener(v->{ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("season",season.getText().toString());x.put("brand",brand.getText().toString());x.put("model",model.getText().toString());x.put("size",size.getText().toString());x.put("purchaseDate",buyDate.getText().toString());x.put("installDate",install.getText().toString());x.put("tread",num(tread.getText().toString()));x.put("pressure",pressure.getText().toString());x.put("storage",storage.getText().toString());x.put("cost",num(cost.getText().toString()));x.put("installed",(int)num(installed.getText().toString()));if(id>0)db.update("tire",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("tire",x);db.log(active,"ШИНЫ",brand.getText().toString()+" "+model.getText().toString(),season.getText().toString());}render();});}
 void documentDialog(){documentDialog(-1);}void documentDialog(long id){LinearLayout l=form();Cursor old=id>0?db.raw("SELECT * FROM document WHERE id=?",new String[]{String.valueOf(id)}):null;final JSONObject o=row(old);if(old!=null)old.close();EditText title=input("Название",o.optString("title","")),type=input("Тип: ОСАГО / КАСКО / СТС / ПТС / Диагностическая карта / другое",o.optString("type","")),issue=input("Дата выдачи",o.optString("issueDate",today())),exp=input("Срок действия YYYY-MM-DD",o.optString("expiryDate","")),note=input("Комментарий",o.optString("note",""));for(EditText e:new EditText[]{title,type,issue,exp,note})l.addView(e);Button file=btn("Прикрепить файл/фото",Color.rgb(64,103,145));l.addView(file);file.setOnClickListener(v->pickFile());Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("document",id));}addDialogCard("Документ",l);save.setOnClickListener(v->{ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("title",title.getText().toString());x.put("type",type.getText().toString());x.put("issueDate",issue.getText().toString());x.put("expiryDate",exp.getText().toString());x.put("note",note.getText().toString());String chosenFile=attachment();x.put("uri",chosenFile.isEmpty()?o.optString("uri",""):chosenFile);if(id>0)db.update("document",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("document",x);db.log(active,"ДОКУМЕНТ",title.getText().toString(),exp.getText().toString());}render();});}
 void partDialog(){partDialog(-1);}void partDialog(long id){LinearLayout l=form();JSONObject o=new JSONObject();Cursor old=id>0?db.raw("SELECT * FROM part WHERE id=?",new String[]{String.valueOf(id)}):null;o=row(old);if(old!=null)old.close();EditText name=input("Название",o.optString("name","")),brand=input("Бренд",o.optString("brand","")),pn=input("Артикул",o.optString("partNumber","")),qty=input("Количество",o.optDouble("quantity",1)+""),price=input("Цена, ₽",fmt(o.optDouble("price",0))),date=input("Дата покупки",o.optString("purchaseDate",today())),supplier=input("Поставщик",o.optString("supplier","")),note=input("Комментарий",o.optString("note",""));for(EditText e:new EditText[]{name,brand,pn,qty,price,date,supplier,note})l.addView(e);Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("part",id));}addDialogCard("Запчасть",l);save.setOnClickListener(v->{ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("name",name.getText().toString());x.put("brand",brand.getText().toString());x.put("partNumber",pn.getText().toString());x.put("quantity",num(qty.getText().toString()));x.put("price",num(price.getText().toString()));x.put("purchaseDate",date.getText().toString());x.put("supplier",supplier.getText().toString());x.put("note",note.getText().toString());if(id>0)db.update("part",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("part",x);db.log(active,"ЗАПЧАСТЬ",name.getText().toString(),fmt(num(price.getText().toString()))+" ₽");}render();});}
 void centerDialog(){centerDialog(-1);}void centerDialog(long id){LinearLayout l=form();JSONObject o=new JSONObject();Cursor old=id>0?db.raw("SELECT * FROM service_center WHERE id=?",new String[]{String.valueOf(id)}):null;o=row(old);if(old!=null)old.close();EditText name=input("Название",o.optString("name","")),addr=input("Адрес",o.optString("address","")),phone=input("Телефон",o.optString("phone","")),site=input("Сайт",o.optString("website","")),note=input("Заметки",o.optString("note",""));for(EditText e:new EditText[]{name,addr,phone,site,note})l.addView(e);Button save=btn("Сохранить",blue);l.addView(save);if(id>0){Button del=btn("Удалить",Color.RED);l.addView(del);del.setOnClickListener(v->confirmDelete("service_center",id));}addDialogCard("Сервис / СТО",l);save.setOnClickListener(v->{ContentValues x=new ContentValues();x.put("vehicleId",active);x.put("name",name.getText().toString());x.put("address",addr.getText().toString());x.put("phone",phone.getText().toString());x.put("website",site.getText().toString());x.put("note",note.getText().toString());if(id>0)db.update("service_center",x,"id=?",new String[]{String.valueOf(id)});else{db.insert("service_center",x);db.log(active,"СЕРВИС",name.getText().toString(),addr.getText().toString());}render();});}
 void documentScreen(){header("Документы", "Сроки действия и файлы");Button a=btn("+ Добавить документ",blue);a.setOnClickListener(v->documentDialog());add(a);addGap(10);Cursor c=db.all("document",active);try{if(!c.moveToFirst()){empty("Документы ещё не добавлены",this::documentDialog);return;}do{long id=c.getLong(0);LinearLayout x=card();String exp=c.getString(c.getColumnIndexOrThrow("expiryDate"));String state=exp.isEmpty()?"Без срока":(exp.compareTo(today())<0?"ИСТЁК":(exp.equals(today())?"СЕГОДНЯ":exp));TextView h=text(c.getString(c.getColumnIndexOrThrow("title")),14,true);h.setTextColor(exp.compareTo(today())<0&&!exp.isEmpty()?Color.rgb(255,74,88):fg());x.addView(h);x.addView(small(c.getString(c.getColumnIndexOrThrow("type"))+" · "+state));Button e=btn("Изменить",blue);e.setOnClickListener(v->documentDialog(id));x.addView(e);add(x);addGap(7);}while(c.moveToNext());}finally{c.close();}}
 void tireScreen(){header("Шины","Комплекты и установка");Button a=btn("+ Добавить комплект",blue);a.setOnClickListener(v->tireDialog());add(a);addGap(10);Cursor c=db.all("tire",active);try{if(!c.moveToFirst()){empty("Комплекты шин ещё не добавлены",this::tireDialog);return;}do{long id=c.getLong(0);LinearLayout x=card();x.addView(text(c.getString(c.getColumnIndexOrThrow("season"))+" · "+c.getString(c.getColumnIndexOrThrow("brand"))+" "+c.getString(c.getColumnIndexOrThrow("model")),14,true));x.addView(small(c.getString(c.getColumnIndexOrThrow("size"))+" · протектор "+fmt(c.getDouble(c.getColumnIndexOrThrow("tread")))+" мм"));x.addView(small(c.getInt(c.getColumnIndexOrThrow("installed"))==1?"УСТАНОВЛЕН":"Не установлен"));Button e=btn("Изменить",blue);e.setOnClickListener(v->tireDialog(id));x.addView(e);Button installBtn=btn(c.getInt(c.getColumnIndexOrThrow("installed"))==1?"Установлен":"Установить",c.getInt(c.getColumnIndexOrThrow("installed"))==1?Color.rgb(40,207,147):blue);installBtn.setEnabled(c.getInt(c.getColumnIndexOrThrow("installed"))!=1);installBtn.setOnClickListener(v->{ContentValues off=new ContentValues();off.put("installed",0);db.update("tire",off,"vehicleId=?",new String[]{String.valueOf(active)});ContentValues on=new ContentValues();on.put("installed",1);on.put("installDate",today());db.update("tire",on,"id=?",new String[]{String.valueOf(id)});db.log(active,"ШИНЫ","Комплект установлен",c.getString(c.getColumnIndexOrThrow("brand"))+" "+c.getString(c.getColumnIndexOrThrow("model")));render();});x.addView(installBtn);add(x);addGap(7);}while(c.moveToNext());}finally{c.close();}}
 void issueScreen(){header("Проблемы","Журнал, а не искусственная диагностика");Button a=btn("+ Добавить проблему",Color.rgb(255,74,88));a.setOnClickListener(v->issueDialog());add(a);addGap(10);Cursor c=db.all("issue",active);try{if(!c.moveToFirst()){empty("Проблем пока нет",this::issueDialog);return;}do{long id=c.getLong(0);LinearLayout x=card();x.addView(text(c.getString(c.getColumnIndexOrThrow("title")),14,true));x.addView(small(c.getString(c.getColumnIndexOrThrow("status"))+" · "+c.getString(c.getColumnIndexOrThrow("date"))+" · "+fmt(c.getDouble(c.getColumnIndexOrThrow("mileage")))+" км"));x.addView(small(c.getString(c.getColumnIndexOrThrow("description"))));Button e=btn("Изменить",blue);e.setOnClickListener(v->issueDialog(id));x.addView(e);add(x);addGap(7);}while(c.moveToNext());}finally{c.close();}}
 void partScreen(){header("Запчасти","Учёт покупок и связей с обслуживанием");Button a=btn("+ Добавить запчасть",blue);a.setOnClickListener(v->partDialog());add(a);addGap(10);Cursor c=db.all("part",active);try{if(!c.moveToFirst()){empty("Запчасти ещё не добавлены",this::partDialog);return;}do{long id=c.getLong(0);LinearLayout x=card();x.addView(text(c.getString(c.getColumnIndexOrThrow("name")),14,true));x.addView(small(c.getString(c.getColumnIndexOrThrow("brand"))+" · "+c.getString(c.getColumnIndexOrThrow("partNumber"))));x.addView(small("Количество: "+c.getDouble(c.getColumnIndexOrThrow("quantity"))+" · "+money(c.getDouble(c.getColumnIndexOrThrow("price")))+" ₽"));Button e=btn("Изменить",blue);e.setOnClickListener(v->partDialog(id));x.addView(e);add(x);addGap(7);}while(c.moveToNext());}finally{c.close();}}
 void centerScreen(){header("Сервисы / СТО","Без выдуманных рейтингов и отзывов");Button a=btn("+ Добавить сервис",blue);a.setOnClickListener(v->centerDialog());add(a);addGap(10);Cursor c=db.all("service_center",active);try{if(!c.moveToFirst()){empty("Сервисы ещё не добавлены",this::centerDialog);return;}do{long id=c.getLong(0);LinearLayout x=card();x.addView(text(c.getString(c.getColumnIndexOrThrow("name")),14,true));x.addView(small(c.getString(c.getColumnIndexOrThrow("address"))));x.addView(small(c.getString(c.getColumnIndexOrThrow("phone"))));Button e=btn("Изменить",blue);e.setOnClickListener(v->centerDialog(id));x.addView(e);add(x);addGap(7);}while(c.moveToNext());}finally{c.close();}}
 void statisticsScreen(){header(t("Статистика","Statistics"),t("Только фактические записи базы","Database records only"));LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.HORIZONTAL);int[] days={7,30,90,365,0};String[] labels={"7д","30д","90д","1г","Всё"};for(int i=0;i<labels.length;i++){final int d=days[i];Button b=btn(labels[i],periodDays==d?blue:Color.rgb(55,78,104));b.setTextSize(11);b.setOnClickListener(v->{periodDays=d;render();});p.addView(b,new LinearLayout.LayoutParams(0,dp(45),1){{setMargins(dp(2),0,dp(2),0);}});}add(p);addGap(10);double e=sumPeriod("expense","amount"),f=sumPeriod("fuel","total"),s=sumPeriod("service","cost");LinearLayout a=card();a.addView(text("Расходы",18,true));a.addView(text(money(e+f+s)+" ₽",29,true));a.addView(small("ТО "+money(s)+" ₽ · топливо "+money(f)+" ₽ · прочее "+money(e)+" ₽"));add(a);addGap(8);LinearLayout b=card();b.addView(text("Топливо",18,true));b.addView(text(periodDays>0?String.format(Locale.getDefault(),"%.1f л",sumPeriod("fuel","liters")):String.format(Locale.getDefault(),"%.1f л",sum("fuel","liters")),27,true));b.addView(small("Средний расход: "+consumption()+" л/100 км"));add(b);addGap(8);LinearLayout c=card();c.addView(text("Пробег",18,true));c.addView(text(distance()>0?fmt(distance())+" км":"Недостаточно данных",27,true));c.addView(small("Стоимость/км: "+costKm()+" ₽/км"));add(c);addGap(10);if(e+f+s<=0)add(small("Недостаточно данных для графиков за выбранный период."));}
void searchScreen(){header("Поиск","Поиск по локальной базе активного автомобиля");EditText q=input("Введите запрос…","");add(q);LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);add(results);Runnable run=()->{results.removeAllViews();String needle=q.getText().toString().trim();if(needle.isEmpty()){results.addView(small("Введите текст для поиска"));return;}String[] tables={"service","fuel","expense","reminder","issue","tire","document","part","service_center"};for(String table:tables){Cursor c=db.all(table,active);try{while(c.moveToNext()){StringBuilder z=new StringBuilder();for(int i=0;i<c.getColumnCount();i++){String s=c.getString(i);if(s!=null)z.append(' ').append(s);}if(z.toString().toLowerCase(Locale.ROOT).contains(needle.toLowerCase(Locale.ROOT))){LinearLayout card=card();card.addView(text(table+" · "+z.toString().trim(),13,true));results.addView(card);Space sp=new Space(this);results.addView(sp,new LinearLayout.LayoutParams(1,dp(6)));}}}finally{c.close();}}};q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){run.run();}public void afterTextChanged(Editable e){}});run.run();}
 void reminderScreen(){header("Напоминания","Дата / пробег / повтор");Button a=btn("+ Добавить напоминание",blue);a.setOnClickListener(v->reminderDialog());add(a);addGap(10);Cursor c=db.all("reminder",active);try{if(!c.moveToFirst()){empty("Нет активных напоминаний",this::reminderDialog);return;}do{long id=c.getLong(0);boolean done=c.getInt(c.getColumnIndexOrThrow("done"))!=0;LinearLayout x=card();x.addView(text(c.getString(c.getColumnIndexOrThrow("title")),14,true));x.addView(small(c.getString(c.getColumnIndexOrThrow("date"))+" · "+(c.getDouble(c.getColumnIndexOrThrow("mileage"))>0?fmt(c.getDouble(c.getColumnIndexOrThrow("mileage")))+" км":"без пробега")));x.addView(small(done?"ВЫПОЛНЕНО":"АКТИВНО"));if(!done){Button doneBtn=btn("Выполнено",Color.rgb(40,180,125));doneBtn.setOnClickListener(v->{ContentValues z=new ContentValues();z.put("done",1);db.update("reminder",z,"id=?",new String[]{String.valueOf(id)});ReminderWorker.cancel(this,id);render();});x.addView(doneBtn);}Button edit=btn("Изменить",blue);edit.setOnClickListener(v->reminderDialog(id));x.addView(edit);add(x);addGap(7);}while(c.moveToNext());}finally{c.close();}}
 void activityScreen(){header("Лента активности","Новые события сверху");Cursor c=db.all("activity",active);try{if(!c.moveToFirst()){empty("История пока пуста",()->{});return;}do{LinearLayout x=card();x.addView(text(c.getString(c.getColumnIndexOrThrow("title")),14,true));x.addView(small(c.getString(c.getColumnIndexOrThrow("kind"))+" · "+c.getString(c.getColumnIndexOrThrow("date"))+" "+c.getString(c.getColumnIndexOrThrow("time"))));x.addView(small(c.getString(c.getColumnIndexOrThrow("detail"))));add(x);addGap(7);}while(c.moveToNext());}finally{c.close();}}
 void editVehicle(){vehicleDialog(false);}
 void switchVehicle(){Cursor c=db.raw("SELECT id,brand,model,mileage FROM vehicle ORDER BY id",null);LinearLayout l=form();try{while(c.moveToNext()){long id=c.getLong(0);Button b=btn(c.getString(1)+" "+c.getString(2)+" · "+fmt(c.getDouble(3))+" км",id==active?blue:Color.rgb(55,78,104));l.addView(b);b.setOnClickListener(v->{active=id;getPreferences(0).edit().putLong("active",id).apply();render();});}}finally{c.close();}if(l.getChildCount()==0){toast("Добавьте автомобиль");return;}addDialogCard("Выбор автомобиля",l);}
 void confirmDeleteVehicle(){new AlertDialog.Builder(this).setTitle("Удалить автомобиль?").setMessage("Будут удалены связанные записи этого автомобиля.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->{String[] tables={"service","fuel","expense","reminder","issue","tire","document","part","service_center","activity"};for(String table:tables)db.delete(table,"vehicleId=?",new String[]{String.valueOf(active)});db.delete("vehicle","id=?",new String[]{String.valueOf(active)});Cursor c=db.raw("SELECT id FROM vehicle ORDER BY id LIMIT 1",null);try{active=c.moveToFirst()?c.getLong(0):-1;}finally{c.close();}getPreferences(0).edit().putLong("active",active).apply();if(active<0)showWelcome();else render();}).show();}
 void confirmDelete(String table,long id){new AlertDialog.Builder(this).setTitle("Удалить запись?").setMessage("Это действие нельзя отменить.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->{db.delete(table,"id=?",new String[]{String.valueOf(id)});if("reminder".equals(table))ReminderWorker.cancel(this,id);render();}).show();}
 void pickPhoto(){Intent i;if(Build.VERSION.SDK_INT>=33)i=new Intent("android.provider.action.PICK_IMAGES");else{i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);}startActivityForResult(i,PICK_PHOTO);}
 void pickFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_FILE);}
 JSONObject buildBackupJson(){try{JSONObject r=new JSONObject();r.put("schemaVersion",2);r.put("appVersion","2.1.3");r.put("exportedAt",System.currentTimeMillis());JSONObject settings=new JSONObject();settings.put("light",light);settings.put("lang",lang);settings.put("activeVehicleId",active);r.put("settings",settings);String[] tables={"vehicle","service","fuel","expense","reminder","issue","tire","document","part","service_center","activity"};for(String table:tables){JSONArray a=new JSONArray();Cursor c=db.raw("SELECT * FROM "+table,null);try{while(c.moveToNext()){JSONObject o=new JSONObject();for(int i=0;i<c.getColumnCount();i++)o.put(c.getColumnName(i),c.getString(i));a.put(o);}}finally{c.close();}r.put(table,a);}return r;}catch(Exception e){throw new IllegalStateException(e);}}
void exportBackup(){try{String json=buildBackupJson().toString(2);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"AUTO_HUB_backup.json");getPreferences(0).edit().putString("backup_pending",json).apply();startActivityForResult(i,9001);}catch(Exception e){toast("Ошибка экспорта");}}
void exportFullBackup(){try{JSONObject json=buildBackupJson();File zipFile=new File(getCacheDir(),"AUTO_HUB_full_backup.zip");ZipOutputStream zos=new ZipOutputStream(new FileOutputStream(zipFile));ZipEntry je=new ZipEntry("backup.json");zos.putNextEntry(je);zos.write(json.toString(2).getBytes("UTF-8"));zos.closeEntry();File dir=new File(getFilesDir(),"attachments");if(dir.exists()){File[] files=dir.listFiles();if(files!=null)for(File file:files){if(!file.isFile())continue;ZipEntry e=new ZipEntry("attachments/"+file.getName());zos.putNextEntry(e);FileInputStream in=new FileInputStream(file);byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)zos.write(buf,0,n);in.close();zos.closeEntry();}}zos.close();getPreferences(0).edit().putString("full_backup_pending",zipFile.getAbsolutePath()).apply();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,"AUTO_HUB_full_backup.zip");startActivityForResult(i,9002);}catch(Exception e){toast("Не удалось создать полную копию");}}
void importBackup(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT);}
void importFullBackup(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/zip");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,9003);}
void importData(Uri uri){try{InputStream in=getContentResolver().openInputStream(uri);BufferedReader br=new BufferedReader(new InputStreamReader(in));StringBuilder b=new StringBuilder();String z;while((z=br.readLine())!=null)b.append(z);br.close();JSONObject r=new JSONObject(b.toString());if(r.optJSONArray("vehicle")==null)throw new JSONException("vehicle missing");new AlertDialog.Builder(this).setTitle("Импорт данных").setMessage("Выберите режим. Merge добавит данные. Replace сначала очистит локальную базу после успешной проверки JSON.").setNegativeButton("Отмена",null).setNeutralButton("Merge",(d,w)->applyImport(r,false)).setPositiveButton("Replace",(d,w)->applyImport(r,true)).show();}catch(Exception e){toast("Файл не распознан или повреждён");}}
 void applyImport(JSONObject r,boolean replace){android.database.sqlite.SQLiteDatabase raw=db.getWritableDatabase();raw.beginTransaction();try{if(r.optInt("schemaVersion",1)>2)throw new JSONException("unsupported schema");String[] tables={"service","fuel","expense","reminder","issue","tire","document","part","service_center","activity","vehicle"};if(replace){for(String table:tables)raw.delete(table,null,null);active=-1;}Map<Long,Long> map=new HashMap<>();JSONArray va=r.optJSONArray("vehicle");if(va!=null)for(int i=0;i<va.length();i++){JSONObject o=va.getJSONObject(i);long oldId=o.optLong("id",-1);ContentValues v=new ContentValues();for(Iterator<String> it=o.keys();it.hasNext();){String k=it.next();if("id".equals(k))continue;Object q=o.get(k);if(q==JSONObject.NULL)continue;if(q instanceof Number)v.put(k,q.toString());else v.put(k,String.valueOf(q));}long newId=db.insert("vehicle",v);if(oldId>0)map.put(oldId,newId);if(active<0)active=newId;}String[] dataTables={"service","fuel","expense","reminder","issue","tire","document","part","service_center","activity"};for(String table:dataTables){JSONArray a=r.optJSONArray(table);if(a==null)continue;for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);ContentValues v=new ContentValues();long oldVehicle=o.optLong("vehicleId",-1);for(Iterator<String> it=o.keys();it.hasNext();){String k=it.next();if("id".equals(k)||"vehicleId".equals(k))continue;Object q=o.get(k);if(q==JSONObject.NULL)continue;if(q instanceof Number)v.put(k,q.toString());else v.put(k,String.valueOf(q));}Long mapped=map.get(oldVehicle);if(mapped==null&&oldVehicle>0)throw new JSONException("vehicle link missing");v.put("vehicleId",mapped!=null?mapped:active);db.insert(table,v);}}raw.setTransactionSuccessful();getPreferences(0).edit().putLong("active",active).apply();toast("Импорт выполнен");if(active>0)render();else showWelcome();}catch(Exception e){toast("Импорт не выполнен: данные не изменены");}finally{raw.endTransaction();}}
void importZip(Uri uri){File tmp=new File(getCacheDir(),"autohub_import");deleteTree(tmp);tmp.mkdirs();try{InputStream in=getContentResolver().openInputStream(uri);ZipInputStream zis=new ZipInputStream(in);ZipEntry e;while((e=zis.getNextEntry())!=null){String name=e.getName();if(name.contains("..")||name.startsWith("/")||(!name.equals("backup.json")&&!name.startsWith("attachments/")))continue;File out=new File(tmp,name);if(e.isDirectory()){out.mkdirs();continue;}File parent=out.getParentFile();if(parent!=null)parent.mkdirs();FileOutputStream os=new FileOutputStream(out);byte[] buf=new byte[8192];int n;while((n=zis.read(buf))!=-1)os.write(buf,0,n);os.close();}zis.close();File jsonFile=new File(tmp,"backup.json");if(!jsonFile.isFile())throw new IOException("backup.json missing");File att=new File(tmp,"attachments");File target=new File(getFilesDir(),"attachments");target.mkdirs();File[] files=att.listFiles();if(files!=null)for(File file:files){if(file.isFile())copyFile(file,new File(target,file.getName()));}String json=readText(jsonFile);JSONObject obj=new JSONObject(json);new AlertDialog.Builder(this).setTitle("Импорт полной копии").setMessage("Выберите режим. Replace заменит локальные данные после успешной проверки архива.").setNegativeButton("Отмена",null).setNeutralButton("Merge",(d,w)->applyImport(obj,false)).setPositiveButton("Replace",(d,w)->applyImport(obj,true)).show();}catch(Exception e){toast("Архив не распознан или повреждён");}finally{deleteTree(tmp);}}
String readText(File f)throws IOException{StringBuilder b=new StringBuilder();BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(f),"UTF-8"));String line;while((line=r.readLine())!=null)b.append(line);r.close();return b.toString();}
void copyFile(File a,File b)throws IOException{FileInputStream in=new FileInputStream(a);FileOutputStream out=new FileOutputStream(b);byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();out.close();}
void deleteTree(File f){if(f==null||!f.exists())return;if(f.isDirectory()){File[] fs=f.listFiles();if(fs!=null)for(File x:fs)deleteTree(x);}f.delete();}


String resolveAttachment(String value){
    if(value==null||value.trim().isEmpty()) return "";
    String v=value.trim();
    if(v.startsWith("/")) return v;
    if(v.startsWith("content://")||v.startsWith("file://")||v.startsWith("android.resource://")) return v;
    File f=new File(getFilesDir(),"attachments/"+v);
    return f.exists()?f.getAbsolutePath():v;
}
String copyAttachmentToApp(Uri uri,String kind)throws IOException{
    if(uri==null)throw new IOException("empty uri");
    File dir=new File(getFilesDir(),"attachments");
    if(!dir.exists()&&!dir.mkdirs())throw new IOException("attachments directory unavailable");
    String mime=getContentResolver().getType(uri);
    String ext="";
    if(mime!=null){
        int slash=mime.lastIndexOf('/');
        if(slash>=0&&slash<mime.length()-1)ext="."+mime.substring(slash+1).replaceAll("[^A-Za-z0-9]","");
    }
    if(ext.isEmpty()){
        String name=null; Cursor c=null;
        try{c=getContentResolver().query(uri,new String[]{android.provider.OpenableColumns.DISPLAY_NAME},null,null,null);if(c!=null&&c.moveToFirst())name=c.getString(0);}finally{if(c!=null)c.close();}
        if(name!=null){int dot=name.lastIndexOf('.');if(dot>=0)ext=name.substring(dot).replaceAll("[^A-Za-z0-9.]","");}
    }
    if(ext.length()>10)ext=ext.substring(0,10);
    String safeKind=(kind==null||kind.isEmpty())?"file":kind.replaceAll("[^A-Za-z0-9_-]","");
    File out=new File(dir,System.currentTimeMillis()+"_"+safeKind+ext);
    InputStream in=getContentResolver().openInputStream(uri);
    if(in==null)throw new IOException("cannot open attachment");
    try(FileOutputStream os=new FileOutputStream(out)){
        byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)os.write(buf,0,n);
    }finally{in.close();}
    return out.getAbsolutePath();
}
@Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK||data==null)return;if(r==9001){try{OutputStream out=getContentResolver().openOutputStream(data.getData());out.write(getPreferences(0).getString("backup_pending","{}").getBytes("UTF-8"));out.close();toast("Резервная копия сохранена");}catch(Exception e){toast("Не удалось сохранить резервную копию");}}else if(r==9002){try{File src=new File(getPreferences(0).getString("full_backup_pending",""));OutputStream out=getContentResolver().openOutputStream(data.getData());FileInputStream in=new FileInputStream(src);byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();out.close();toast("Полная копия сохранена");}catch(Exception e){toast("Не удалось сохранить полную копию");}}else if(r==IMPORT)importData(data.getData());else if(r==9003)importZip(data.getData());else if(r==PICK_PHOTO||r==PICK_FILE){try{pendingAttachment=copyAttachmentToApp(data.getData(),r==PICK_PHOTO?"photo":"file");getPreferences(0).edit().putString("pending_attachment",pendingAttachment).apply();toast("Файл выбран");}catch(Exception e){toast("Не удалось сохранить вложение");}}}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 @Override public void onBackPressed(){if(screen!=0){screen=0;render();}else super.onBackPressed();}
}
